from MaxMods.Matrix import *

mat = Matrix([[1,2],[3,4]])
mat.print()
mat.index(0, 1, 0).print()
mat2 = Matrix(mat.copy())
mat2.modular(2).print()
mat.rotate(1).print()
mat.flip(1).print()
mat.flip(2).print()
Multiply(mat, mat2).print()
mat.print()
print(mat[0])
Add(mat, mat2).print()
mat.index(0,0,2).index(0,1,2).index(1,0,2).index(1,1,2).print()
print(f'Average = {mat.average()}\n')
print(f'Sum = {mat.sum()}\n')