from cryptography.fernet import Fernet
import requests
import warnings

class LocationError(BaseException): ...
class AuthenticationError(BaseException): ...
class UsernameError(AuthenticationError): ...
class PasswordError(AuthenticationError): ...
class SaveError(BaseException): ...